# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title

# Setup
title:            Adrien HumiliÃ¨re
tagline:          'iOS & macOS developer'
description:      'ğŸ‘‹ Hi! I am an iOS/macOS developer and team lead from Paris, France.<br/>If you want to know more about me, please have a look at my <a href="/resume">resume</a> and <a href="http://github.com/adhumi">Github</a> or <a href="http://twitter.com/adhumi">Twitter</a> accounts.'
url:              https://adhumi.fr
baseurl:          '/'
paginate:         5
credits:          Crafted with &lt;3 by adhumi
emoji:            ğŸƒâ€â™‚ï¸

author:
  name:           'Adrien HumiliÃ¨re'
  url:            https://twitter.com/adhumi

# Custom vars
github:
  repo:           https://github.com/adhumi/adhumi.fr

# Exclude
exclude:          [vendor, readlist.md]

# SEO
seo-description:  'I am an iOS/macOS developer and team lead from Paris, France.'
seo-keywords:     'developer, objective-c, swift, apple, ios, edjing, captain train, brut'

# Gems
plugins:
  - jekyll-paginate
