# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title

# Setup
title:            Adrien HumiliÃ¨re
tagline:          'iOS developer'
description:      'Hi! I am an iOS developer from Paris, France. I craft code at <a href="https://www.brut.media">Brut</a>. I teach iOS development to students at UPMC.<br/>If you want to know more about me, please have a look at my <a href="/resume">resume</a> and <a href="http://github.com/adhumi">Github</a> or <a href="http://twitter.com/adhumi">Twitter</a> accounts.'
url:              https://adhumi.fr
baseurl:          '/'
paginate:         5
credits:          Crafted with &lt;3 by adhumi
emoji:            ðŸš‚

author:
  name:           'Adrien HumiliÃ¨re'
  url:            https://twitter.com/adhumi

# Custom vars
github:
  repo:           https://github.com/adhumi/adhumi.fr

# Exclude
exclude:          [vendor, readlist.md]

# SEO
seo-description:  'I am an iOS developer from Paris, France. I craft code at Brut and and I teach iOS development to students at UPMC.'
seo-keywords:     'developer, objective-c, swift, apple, ios, edjing, captain train, brut'

# Gems
plugins:
  - jekyll-paginate
